# 这里填写宿主机地址,如果不使用docker,就和base_path相同
prover_host_path = "./"

# 1. 如果使用docker启动,这里填写容器内的路径,
#   参照docker-compose中,就是/home/ubuntu/pozk
# 2. 如果不使用docker,这里填写宿主机路径
# use docker
#base_path = "/home/ubuntu/pozk"
# not docker
base_path = "./"


db_remove = false
endpoint = "https://opbnb-testnet-rpc.bnbchain.org"
open_monitor = true

[monitor_config]
task_address = "0x27DE7777C1c643B7F3151F7e4Bd3ba5dacc62793"
prover_address = "0x1c23e9F06b10f491e86b506c025080C96513C9f5"
stake_address = "0x003C1F8F552EE2463e517FDD464B929F8C0bFF06"
from = 0
delay_sec = 0
step = 10
wait_time = 10
block_number_type = "latest"
miner = "0x28B9FEAE1f3d76565AAdec86E7401E815377D9Cc"
docker_proxy_prefix = "docker.registry.cyou"

[api_config]
host = "0.0.0.0"
port = 9098
login_domain = "localhost:4000"