version: '3'

services:
  pozk-miner:
    image: zyphernetwork/pozk-miner:0.0.14
    container_name: pozk-miner
    ports:
      - "9098:9098"
    volumes:
      - ./:/usr/pozk
      - /var/run/docker.sock:/var/run/docker.sock
    command:
      - --miner=0x0000000000000000000000000000000000000000
      - --endpoint=https://linea-testnet-zytron.zypher.game
      - --network=testnet
      # - --config=/usr/pozk/config.toml # advance configure, default is none
      # - --host_base_path=/usr/pozk # change host base path for docker use, default is /usr/pozk
      # - --docker_base_path=/usr/pozk # keep same with volumes's params

  pozk-frontend:
    image: zyphernetwork/pozk-frontend:0.0.5
    container_name: pozk-frontend
    ports:
      - "4000:4000"
    environment:
      - API_BASE_URL=http://localhost:9098/api
      - NETWORK=testnet
