version: '3'

networks:
  default:
    name: pozk

services:
  pozk-miner:
    image: zyphernetwork/pozk-miner:0.0.17
    container_name: pozk-miner
    ports:
      - "9098:9098"
    volumes:
      - ./:/usr/pozk
      - /var/run/docker.sock:/var/run/docker.sock
    command:
      - --miner=0x0000000000000000000000000000000000000000
      - --endpoints=https://linea-mainnet-zytron.zypher.game
      - --network=testnet
      # - --config=/usr/pozk/config.toml # advance configure, default is none
      # - --base-path=/usr/pozk # change host base path for docker use, default is /usr/pozk
      # - --server=http://pozk-miner:9098 # the pozk-miner server with default networks: pozk
      # - --docker-proxy=xxx # if need use docker proxy server
      # - --zero-gas=xxx # if need other zero gas server uri, default is zytron 0 gas service

  pozk-frontend:
    image: zyphernetwork/pozk-frontend:0.0.11
    container_name: pozk-frontend
    ports:
      - "4000:4000"
    environment:
      - API_BASE_URL=http://localhost:9098
      - NETWORK=testnet
